### ISSUE TITLE
If gamecounts loaded from file are too high, program errors.

### ISSUE THREAD

**Issue by hsgarn** [hsgarn/foosobsplus#13]
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 7 >= 4
	at java.util.Vector.elementAt(Unknown Source)
	at javax.swing.table.DefaultTableColumnModel.getColumn(Unknown Source)
	at sun.swing.SwingUtilities2.convertColumnIndexToModel(Unknown Source)
	at javax.swing.JTable.convertColumnIndexToModel(Unknown Source)
	at javax.swing.JTable.setValueAt(Unknown Source)
	at com.midsouthfoosball.foosobsplus.view.MatchPanel.setTime(MatchPanel.java:215)
	at com.midsouthfoosball.foosobsplus.controller.MatchController$GameClockTimerListener.actionPerformed(MatchController.java:77

Start Match button will allow program to continue properly.  Need to find a way to protect from high numbers or ignore numbers that are too high when setting the currentGameNumber which I suspect is where the issue might be.

**Comment by hsgarn** [comment]
Fixed in version 1.056
